version: 2
updates:
- package-ecosystem: nuget
  directory: "/"
  schedule:
    interval: daily
    time: "03:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: Microsoft.EntityFrameworkCore.Tools
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
    - 5.0.5
  - dependency-name: Syncfusion.Blazor
    versions:
    - 18.4.0.39
    - 18.4.0.41
    - 18.4.0.42
    - 18.4.0.43
    - 18.4.0.44
    - 18.4.0.46
    - 18.4.0.47
    - 18.4.0.48
    - 18.4.0.49
    - 19.1.0.54
  - dependency-name: Blazorise.Bootstrap
    versions:
    - 0.9.2.5
    - 0.9.3
    - 0.9.3.1
    - 0.9.3.2
    - 0.9.3.3
  - dependency-name: Microsoft.EntityFrameworkCore.Sqlite
    versions:
    - 5.0.2
    - 5.0.3
    - 5.0.4
  - dependency-name: Microsoft.NET.Test.Sdk
    versions:
    - 16.8.3
    - 16.9.1
  - dependency-name: Microsoft.CodeAnalysis
    versions:
    - 3.8.0
  - dependency-name: Hangfire
    versions:
    - 1.7.19
  - dependency-name: System.Text.Json
    versions:
    - 5.0.1
